services:
  - type: web
    name: smartgalpon-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "cd bd_Smartgalpon_api && gunicorn bd_Smartgalpon.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      # Configuraci√≥n de base de datos - IMPORTANTE
      - key: DATABASE_URL
        sync: false  # Esto debes configurarlo en el dashboard de Render
