services:
  - type: web
    name: smartgalpon-api
    env: python
    plan: free
    buildCommand: "cd bd_Smartgalpon_api && pip install -r ../requirements.txt"
    startCommand: "cd bd_Smartgalpon_api && gunicorn bd_Smartgalpon.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        sync: false  # IMPORTANTE: Aquí pondrás tu URL de Supabase
